### ISSUE TITLE
Text color does not display in Firefox.

### ISSUE THREAD

**Issue by Milo-kinkyswan** [milovana/eos-issues#2]
This bug pertains to text color applied within the Say action. In Firefox browser, the applied text color displays in the editor, but not in Preview or published tease.

Apparent cause of the bug is the content-security-policy for the page https://eosscript.com. Relevant portion:

`content-security-policy: default-src 'none'; style-src https://eosscript.com;`

### Example
In Google Chrome, this is an example of HTML for text rendered by the Say action during a preview:

`<span style="color: rgb(253, 216, 53);">Hello, world!</span>`

In Firefox, the same text rendered by the Say action during a preview renders thusly:

`<span>Hello, world!</span>`

and at the same time generates the console error:

`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”).`

The error makes sense, given that the content security policy does not include `'unsafe-inline'` for the `style-src`. i.e. inline styles have not been allowed.

### Suggestion

Use classes for the text color rather than inline styles. As it is, many of the colors currently available are so subtly different as to be indistinguishable. I would guess that a set of ten or so colors would be sufficient for everyone's needs.

**Comment by fapnip** [comment]
Can't replicate this.  Guessing it's been fixed in either a newer version of FireFox or new version of Eos.  Closing.
