### ISSUE TITLE
Unable to create new EOS tease

### ISSUE THREAD

**Issue by fapnip** [milovana/eos-issues#4]
**Describe the bug**
Since July, users are unable to create new teases in the EOS editor.

**To Reproduce**
1. Open EOS editor
2. Go to list of teases
3. Click "Create Tease", enter information and click "Create Tease"
4. No new tease ID is assigned, and you are directed to : https://milovana.com/eos/editor/null/edit

**Expected behavior**
New tease should be created

**Additional context**
Seems to affect all users.

**Comment by seraph0x** [comment]
Thanks for reporting. :+1: This issue has since been fixed.
